Queries
ikoote1/vet_clinic pull request #7
Opened 2023-05-09 10:48 UTC by ikoote1

Changes made to the database;
1. Confirmed that the following queries take too much time (1 sec = 1000ms can be considered too much time for a database query) using explain analyze.
- EXPLAIN ANALYZE  SELECT COUNT(*) FROM visits where animal_id = 4;
![mis1](https://github.com/ikoote1/vet_clinic/assets/96288581/c44d6f38-b6f6-4328-a52c-f519bfc3f686)
- EXPLAIN ANALYZE  SELECT * FROM visits where vet_id = 2;
![mis2](https://github.com/ikoote1/vet_clinic/assets/96288581/fc6ab1b9-f528-4758-b08d-4890a996ce89)
- EXPLAIN ANALYZE  SELECT * FROM owners where email = 'owner_18327@mail.com';
![mis3](https://github.com/ikoote1/vet_clinic/assets/96288581/409c5063-e132-4384-9270-dcc6a3f7b0b4)

2. Decreased the execution time of the first query by creating a new index.
![mis4](https://github.com/ikoote1/vet_clinic/assets/96288581/c1ffc6f1-d365-40c9-8280-1b3365b38b15)
3. Improved execution time of the other two queries.
4. Opened a pull request.

Thanks for reviewing my code.

2023-05-09 10:57 UTC, Olamarx requested changes
Hi @ikoote1,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the commit of your partner, kindly make sure your partner contributes to the project so that you both can learn from this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-09 12:54 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

![invalid-submission](https://user-images.githubusercontent.com/93039359/221218445-05489541-f840-492c-878e-0587cc2b3702.gif)

## Hey @ikoote1, @MuhammadUsmanAslam :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 12:54 UTC, HAMMAS-SALEEM commented on data.sql
> +
- [x] It would be nice if you make your pull request title more descriptive 👍 such as **Vet clinic database: database performance audit** instead of **Queries** to make your pull request descriptive enough 😊

2023-05-09 12:54 UTC, HAMMAS-SALEEM commented on data.sql
> +
![image](https://github.com/ikoote1/vet_clinic/assets/93039359/f91e5985-93fd-4593-a9fe-f5f32fe000e2)
![image](https://github.com/ikoote1/vet_clinic/assets/93039359/17339bd9-3918-44f7-91ee-1766863e4734)

- [x] It would be nice if you remove these section descriptions from your readme file to make your readme descriptive enough 👍

2023-05-09 13:59 UTC, addod19 requested changes
### Hi @ikoote1 and @MuhammadUsmanAslam, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] README file looks professional and has all relevant headers :1st_place_medal: 



## Required Changes ♻️
_Check the comments under the review._
- [x] It would be better if we add the 2 other screenshots for `vets_id=2` and `email = 'owner_18327@mail.com'` for the improved execution time of these queries

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing all commit messages :man_technologist: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 13:59 UTC, addod19 commented on schema.sql
>  CREATE TABLE vets (ID int GENERATED ALWAYS AS INDENITY, name VARCHAR NOT NULL, age INT NOT NULL, date_of_graduation date NOT NULL, PRIMARY KEY(id) );
- [x] It would be better if we add an extra column to the `owners` table and the extra column should be `email` and it should be in the `schema.sql` file. **NB**: `Everything that creates or change the tables structure should be saved in the schema.sql file` as we have in the project requirements
![Screenshot from 2023-05-09 13-42-17](https://github.com/ikoote1/vet_clinic/assets/46388113/505e513b-173f-4a90-b16c-26be107a18cc)

![Screenshot from 2023-05-09 13-43-17](https://github.com/ikoote1/vet_clinic/assets/46388113/e8258ec5-11e8-4956-8378-b652a37875ae)

2023-05-09 13:59 UTC, addod19 commented on schema.sql
> +
- [x] It would be better if we create the `indexes` in the schema.sql file

2023-05-10 08:06 UTC, 1GORDON requested changes
##
## Hi @ikoote1 & @MuhammadUsmanAslam ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [x] As requested by the previous reviewer, the 2 other screenshots for vets_id=2 and email = 'owner_18327@mail.com' for the improved execution time are missing the index scan in the query planner output. Could you remove indexes and add them once again? Ensure there is an index scan in the output for the two queries.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 08:54 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @ikoote1 & @MuhammadUsmanAslam ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 08:56 UTC, merged